[2024-07-07T15:05:06.708+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T15:05:07.005+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_V2.third_task scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-07-07T15:05:07.090+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_V2.third_task scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-07-07T15:05:07.099+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-07T15:05:07.304+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): third_task> on 2024-07-05 00:00:00+00:00
[2024-07-07T15:05:07.336+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=285) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-07T15:05:07.352+0000] {standard_task_runner.py:63} INFO - Started process 302 to run task
[2024-07-07T15:05:07.357+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_V2', 'third_task', 'scheduled__2024-07-05T00:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpcayqsxzt']
[2024-07-07T15:05:07.383+0000] {standard_task_runner.py:91} INFO - Job 123: Subtask third_task
[2024-07-07T15:05:07.747+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_V2.third_task scheduled__2024-07-05T00:00:00+00:00 [running]> on host a10fdcb539f4
[2024-07-07T15:05:08.390+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bavenraj' AIRFLOW_CTX_DAG_ID='our_first_dag_V2' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-05T00:00:00+00:00'
[2024-07-07T15:05:08.393+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T15:05:08.522+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-07T15:05:08.551+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task 3 and will be running after task2 !']
[2024-07-07T15:05:08.621+0000] {subprocess.py:86} INFO - Output:
[2024-07-07T15:05:08.628+0000] {subprocess.py:93} INFO - hey, I am task 3 and will be running after task2 !
[2024-07-07T15:05:08.650+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-07T15:05:08.653+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T15:05:08.843+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag_V2, task_id=third_task, run_id=scheduled__2024-07-05T00:00:00+00:00, execution_date=20240705T000000, start_date=20240707T150507, end_date=20240707T150508
[2024-07-07T15:05:08.969+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T15:05:09.034+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-07T15:05:09.099+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
